### ISSUE TITLE
Favor optional daisy registers in Pin traits

### ISSUE THREAD

**Issue by mciantyre** [imxrt-rs/imxrt-iomuxc#31]
Although daisy registers may be required today, #30 shows that daisy registers may be optional tomorrow. Refactor traits and implementations to always use `Option<Daisy>` associated constants. This lets us extend chip support without incurring breaking changes.

After #30, it seems that only [`lpi2c::Pins` needs this treatment](https://github.com/imxrt-rs/imxrt-iomuxc/blob/a11b4e9a2d426508b68dbf36509ee0460bb50649/src/lpi2c.rs#L25).

**Comment by Florob** [comment]
Relatedly, `flexpwm::Pin` doesn't have any daisy register specified. However, everything except the RT 101x seems to need one.

**Comment by mciantyre** [comment]
Thanks for noting the missing PWM daisies. That might've been annoying to find when exploring FlexPWM inputs.
